#!/bin/sh /etc/rc.common
#
#  SAFEGATE AGENT (v.2023.08.08)
#  A product of SCS Cyber Security JSC VietNam.
#  https://safegate.vn/
#

START=50
STOP=50
USE_PROCD=1

PROG_NAME=SafeGate

LUA=/usr/bin/lua

DIRECT_CONFIG=/etc/$PROG_NAME
PATH_EXEC=/usr/share/$PROG_NAME
PROG=$PATH_EXEC/bin/SGAgent.lua
DIRECT_TMP=/tmp/$PROG_NAME
PID_FILE=$DIRECT_TMP/agent.pid

PID=$(cat "$PID_FILE" 2> /dev/null)

AGENT_PROC=SGAgent

status_service() {
   if kill -0 $PID 2> /dev/null; then
      echo "status: service SGAgent is running (pid: $PID)"
   else
      echo "Service $AGENT_PROC is still stopped"
   fi
}

start_service(){
   if kill -0 $PID 2> /dev/null; then
       echo "SGAgent is still started (pid:$PID)"
       exit 0
   else
       [ ! -d "$DIRECT_CONFIG" ] && mkdir -p "$DIRECT_CONFIG"
       [ ! -d "$DIRECT_TMP" ] && mkdir -p "$DIRECT_TMP"

       if [ ! -d "$DIRECT_CONFIG/database" ]; then
           mkdir -p "$DIRECT_CONFIG/database"
       fi

       if [ ! -f "$PID_FILE" ]; then
         touch "$PID_FILE"
       fi

       if [ ! -f "$DIRECT_TMP/agent.log" ]; then
         touch "$DIRECT_TMP/agent.log"
       fi

       procd_open_instance $AGENT_PROC
       procd_set_param command $LUA $PROG $PATH_EXEC
       procd_set_param pidfile $PID_FILE

       procd_set_param respawn "${respawn_threshold:-3600}" "${respawn_timeout:-5}" "${respawn_retry: -5}"
       procd_set_param limits core="unlimited"
       procd_set_param stdout 1
       procd_set_param stderr 1
       procd_set_param term_timeout 5
       procd_close_instance
   fi
}

stop_service(){
  if kill -0 $PID 2> /dev/null; then
    local _pid
    for _pid in $(pidof "$AGENT_PROC")
    do
      [ "$_pid" = "$$" ] && continue
      [ -e "/proc/$_pid/stat" ] && kill "$_pid"
    done
  fi
}

reload_service(){
  stop;
  start;
}

